services:
  backend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./storage:/usr/src/app/storage
      - ./.env:/usr/src/app/.env
    environment:
      - NODE_ENV=development
    command: npm start
